import cover from '../Component/Images/artItem.png'
import cover2 from '../Component/Images/artItem2.png'
export const ARTICLE_DATA = [
    {
        id: '1',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover,
    },
    {
        id: '2',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover2,
    },
    {
        id: '3',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover,
    },
    {
        id: '4',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover2,
    },
    {
        id: '5',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover,
    },
    {
        id: '6',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover2,
    },
    {
        id: '7',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover,
    },
    {
        id: '8',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'Technology',
        tag: 'React',
        cover: cover2,
    },
    {
        id: '9',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'technology',
        tag: 'React',
        cover: cover,
    },
    {
        id: '10',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'technology',
        tag: 'React',
        cover: cover2,
    },
    {
        id: '11',
        title: 'React',
        content: "My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments. I am able to adapt to challenging work and to commit to project development in a short period of time.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'technology',
        tag: 'React',
        cover: cover,
    },

];