import cover from '../Component/Images/artItem.png'
import cover2 from '../Component/Images/artItem2.png'
export const ARTICLE_DATA = [
    {
        id: '1',
        title: 'Frontend Developer',
        description: 'Coding is my passion, and I am always eager to learn new things. ',
        content: `As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.
        My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.
        Coding is my passion, and I am always eager to learn new things.`,
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'technology',
        tag: 'Javascript',
        cover: cover,
    },
    {
        id: '2',
        title: 'Frontend Developer',
        description: 'Open your eye and your mind',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'art',
        tag: 'React',
        cover: cover2,
    },
    {
        id: '3',
        title: 'Frontend Developer',
        description: 'Finding your style,finding yourself',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'fashion',
        tag: 'React',
        cover: cover,
    },
    {
        id: '4',
        title: 'Frontend Developer',
        description: 'Enjoying, loving and sharing',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        views: 100,
        liked: 100,
        comments: 100,
        category: 'life',
        tag: 'Less',
        cover: cover2,
        date: '09/12/2021'
    },
    {
        id: '5',
        title: 'Frontend Developer',
        description: 'Coding is my passion, and I am always eager to learn new things. ',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        views: 100,
        liked: 100,
        comments: 100,
        category: 'technology',
        tag: 'Sass',
        cover: cover,
    },
    {
        id: '6',
        title: 'Frontend Developer',
        description: 'Open your eye and your mind',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'art',
        tag: 'HTML',
        cover: cover2,
    },
    {
        id: '7',
        title: 'Frontend Developer',
        description: 'Finding your style, finding yourself',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'fashion',
        tag: 'React',
        cover: cover,
    },
    {
        id: '8',
        title: 'Frontend Developer',
        description: 'Enjoying, loving and sharing',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'life',
        tag: 'Javascript',
        cover: cover2,
    },
    {
        id: '9',
        title: 'Frontend Developer',
        description: 'Coding is my passion, and I am always eager to learn new things. ',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'technology',
        tag: 'CSS',
        cover: cover,
    },
    {
        id: '10',
        title: 'Frontend Developer',
        description: 'Coding is my passion, and I am always eager to learn new things. ',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'technology',
        tag: 'React',
        cover: cover2,
    },
    {
        id: '11',
        title: 'Frontend Developer',
        description: 'Finding your style,finding yourself',
        content: "As a web application developer, I have acquired the following front-end basics: HTML5, CSS2 & CSS3, as well as CSS pre-processing languages like LESS. I have experience with front-end technologies, including Javascript, ES6, ReactJS, Redux, Bootstrap, etc. I have strong experience utilizing RESTful APIs to exchange data between front-end and back-end systems. I am also proficient in the use of distributed repository tools such as Git and Github.My strengths lie in my ability to learn quickly and have a pleasant disposition, and I can work effectively in dynamic environments.I am able to adapt to challenging work and to commit to project development in a short period of time.Coding is my passion, and I am always eager to learn new things.",
        date: '06/12/2021',
        views: 100,
        liked: 100,
        comments: 100,
        category: 'fashion',
        tag: 'HTML',
        cover: cover,
    },

];